<?php

namespace ContainerHpwYCoM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStoreControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\StoreController' shared autowired service.
     *
     * @return \App\Controller\StoreController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/StoreController.php';

        return $container->services['App\\Controller\\StoreController'] = new \App\Controller\StoreController();
    }
}
