<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHpwYCoM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHpwYCoM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHpwYCoM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHpwYCoM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHpwYCoM\App_KernelDevDebugContainer([
    'container.build_hash' => 'HpwYCoM',
    'container.build_id' => '01fec7c6',
    'container.build_time' => 1788275967,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHpwYCoM');
